---
title: "exp3_analysis"
output: html_document
---

First, import data
```{r}
d0 = read.csv("q_and_a3-trials.tsv", sep = '\t')
d1 = read.csv("../../experiment3_fr/data/q_and_a3_fr-trials.tsv", sep = '\t')
```

We begin by analyzing the 'question' experiment.

```{r}
d0_q = subset(d0, trial_type == 'question', select=c(workerid, qud, response))
d1_q = subset(d1, trial_type == 'question', select=c(workerid, qud, response))
d1_q$response = factor(d1_q$response)
pooled_qs = rbind(d0_q, d1_q)
str(pooled_qs)
```

Now, for a given qud, we want to know the distribution of questions asked (could be pooled with data from other versions, since this was the same in all)

```{r}
new_labels = sapply(X = pooled_qs$qud, FUN = function(v) {return(paste("qud:", v))})
pooled_qs$facet_label = new_labels
g4<-ggplot(pooled_qs, aes(x=response)) + geom_histogram(color="black", fill='black')
g4 + facet_wrap(~facet_label)
```

Next, we evaluate the answers:

Note that participants always tell the truth -- the gate they give always matches the true location of the item they give

```{r}
d0_a = subset(d0, trial_type == 'ans:', 
              select=c(workerid, utterance, world_state, gate_response, item_response))
d0_a$world_state = strsplit(as.character(d0_a$world_state), split = ',')
for(i in 1:dim(d0_a)[1]){
  d0_a$telling_truth = d0_a$gate_response[i] == match(tolower(d0_a$item_response[i]), 
                                                      d0_a$world_state[i][[1]])
}
g4<-ggplot(d0_a, aes(x=item_response)) + geom_histogram(color="black", fill='black')
g4 + facet_wrap(~utterance)
str(e3_a)
```