---
title: "Untitled"
output: html_document
---

To analyze the output of a webppl program for bayesian data analysis

```{r}
setwd("/Users/rxdh/Box Sync/stanford/research/goodman/q&a/modeling")
library(ggplot2)
library(dplyr)
library(coda)
library(purrr)
estimate_mode <- function(s) {
  d <- density(s)
  return(d$x[which.max(d$y)])
}

HPDhi<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","upper"])
}

HPDlo<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","lower"])
}
options("scipen"=10) 
```

### Load in empirical data

```{r message=FALSE}
ps = read.csv("../MultiExperiment2/data/MultiExp2_compiled-subject_information.csv",
              sep = ',', header = TRUE)
mturk = read.csv("../MultiExperiment2/data/MultiExp2_compiled-mturk.csv",
                 sep=',', header= TRUE) %>%
  mutate(gameID = Answer.id) %>%
  select(workerid, gameID)
d = read.csv("../MultiExperiment2/data/MultiExp2_compiled-trials_clean.csv",  
             sep = ',', header = TRUE) %>%
  right_join(mturk, by = 'workerid')
english_ps <- (ps %>% 
               filter(nativeEnglish == "yes"))$workerid
cat("We removed", length(ps$workerid) - length(english_ps), "ps due to language")
#trialsCompleted = d %>% count(workerid) %>% mutate(numCompleted = n)
filteredD = d %>% filter(workerid %in% english_ps) %>% 
       filter(answer != "NA") 
completedGames = (filteredD %>% group_by(gameID) %>% 
                    count(gameID) %>% mutate(numCompleted = n) %>% 
                    filter(numCompleted == 24))$gameID
cat("We removed", length(unique(d$workerid)) - length(completedGames)*2, "games total")
d <- filteredD %>% filter(gameID %in% completedGames) %>% 
     distinct(domain, goal, question, guess, answer, type, gameID)
source("~/Box Sync/stanford/research/goodman/q&a/MultiExperiment2/analysis/analysisHelpers.R")
d <- mapWordsToNodes(d)
d_q = d %>% 
      mutate(response = ordered(questionNodes, levels = c("Q1","Q2","Q3","Q4"))) %>%
      mutate(goal = ordered(goalNodes, levels = c("G1", "G2", "G3", "G4"))) %>%
      group_by(domain, type, goal) %>%
      do(getProbsAndCIs(data = ., QorA = 'q', R = 1000, FALSE)) %>%
      select(goal, type, response, domain, count, lower_ci, upper_ci,
             groupSize, empProb) %>%
      ungroup() %>%
      filter(!(type == "equivocal" & (response == "Q3" | response == "Q4"))) %>%
      mutate(domain = factor(domain),
             type = factor(type),
             goal = ordered(goal, levels=c("G1","G2","G3","G4")))
d_a = d %>% 
      mutate(response=ordered(answerNodes,levels=c("A1","A2","A3","A4"))) %>%
      mutate(utterance=ordered(questionNodes,levels=c("Q1","Q2","Q3","Q4"))) %>%
      group_by(domain, type, utterance) %>%
      do(getProbsAndCIs(data = ., QorA = 'a', R = 1000, FALSE)) %>%
      select(utterance, type, response, domain, count, lower_ci, upper_ci,
             groupSize, empProb) %>%
      ungroup() %>%
      mutate(domain = factor(domain),
             type = factor(type),
             utterance = ordered(utterance, levels=c("Q1","Q2","Q3","Q4")))
```

### Load in model results

```{r}
qparams<-read.csv("guessingGame/Bayesian/data/BayesianQuestionerAnalysis_loose_Params.csv", sep = ",", row.names = NULL)

samples = 1000
qparams %>% 
    filter(parameter == "expVsPrag") %>%
    group_by(value) %>%
    summarize(prob = sum(MCMCprob))

qparams.samples <- qparams[rep(row.names(qparams), qparams$MCMCprob*samples), 1:2] %>%
  filter(parameter != "expVsPrag") %>%
  mutate(value = factorToNumeric(value))

qparams.samples%>%
  ggplot(aes(x = value))+
    geom_histogram(aes(y=..density..), fill = 'white', color = 'black')+
    geom_density(aes(y=..density..), alpha = .2,  fill="#FF6666") +
    facet_wrap(~parameter, scales = 'free') +
    theme_bw()

qparams.samples %>% 
  group_by(parameter) %>%
  summarize(mode = estimate_mode(value),
            md_lo = round(HPDlo(value), 3),
            md_hi = round(HPDhi(value), 3))
```

```{r}
aparams<-read.csv("guessingGame/Bayesian/data/BayesianAnswererAnalysis_loose_params.csv", sep = ",", row.names = NULL)
samples = 1000
str(aparams)
#aparams.samples <- aparams[rep(row.names(aparams), aparams$MCMCprob*samples), 1:2]

aparams %>%
  filter(parameter != "expPragFlip") %>%
  group_by(parameter, value) %>%
  summarize(marg = sum(MCMCprob)) %>%
  mutate(value = as.factor(round(as.numeric(as.character(value)), digits = 2))) %>%
  filter(marg > 10e-9) %>%
  ggplot(aes(x = value, y = marg))+
  geom_bar(stat = 'identity') +
  facet_wrap(~ parameter, scales = 'free') +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
    # geom_histogram(aes(y=..density..), fill = 'white', color = 'black')+
    # geom_density(aes(y=..density..), alpha = .2,  fill="#FF6666") +
    # facet_wrap(~parameter, scales = 'free') +
    # theme_bw()

# aparams.samples %>% 
#   group_by(parameter) %>%
#   summarize(mode = estimate_mode(value),
#             md_lo = round(HPDlo(value), 3),
#             md_hi = round(HPDhi(value), 3))
```

```{r}
# pdf(file="../writing/2015/journal-manuscript/figures/AnswererParamPosteriors.pdf",
#      width = 6, height = 3)
ggplot(aparams.samples, aes(x=value))+
    geom_histogram(aes(y=..density..), data =subset(aparams.samples, parameter == "alpha" ), binwidth = .1, colour="black", fill="white")+
    geom_histogram(aes(y=..density..), data=subset(aparams.samples, parameter == "beta"), binwidth = .035, colour="black", fill="white")+
    geom_density(data =subset(aparams.samples, parameter == "alpha" ), adjust = 1,
                 alpha=.2, fill="#FF6666")+
    geom_density(data=subset(aparams.samples, parameter == "beta"), adjust = 2,
                 alpha=.2, fill="#FF6666")+
    ggtitle("Answerer Parameter Posteriors (1000 iterations)") +
    facet_grid(~parameter, scales = 'free') +
    theme_bw()
# dev.off()
```

### Predictives

```{r}
source("~/Box Sync/stanford/research/goodman/q&a/MultiExperiment2/analysis/analysisHelpers.R")
apredictive<-read.csv("guessingGame/Bayesian/data/BayesianAnswererAnalysisPredictives_betaFlipOutside.csv", sep = ",", row.names = NULL)
apredictive.toplot <- apredictive %>% 
  mutate(question = as.character(parameter),
         answer = substr(as.character(value), 1, nchar(as.character(value)) - 1),
         type = as.character(item1),
         domain = as.character(item2)) %>%
  do(mutate(., answer = vectorizedMapAnswer(type, answer))) %>%
  do(mutate(., question = vectorizedMapQuestion(type, question))) %>%
  mutate(utterance = as.factor(question), response = as.factor(answer)) %>%
  select(type, domain, utterance, response, MCMCprob)

# apredictive.samples <- apredictive[rep(row.names(apredictive), 
#                                        apredictive$MCMCprob*samples), 1:5] %>%
#   mutate(question = as.character(parameter), 
#          answer = substr(as.character(value), 1, nchar(as.character(value)) - 1),
#          type = as.character(item1),
#          domain = as.character(item2)) %>%
#   do(mutate(., answer = vectorizedMapAnswer(type, answer))) %>%
#   do(mutate(., question = vectorizedMapQuestion(type, question))) %>%
#   mutate(utterance = as.factor(question), response = as.factor(answer)) %>% 
#   select(type, domain, utterance, response, prob)

# apredictive.pp <- apredictive.toplot %>%
#   group_by(type, domain, utterance, response) %>%
#   summarize(MAP = estimate_mode(prob),
#             credHigh = HPDhi(prob),
#             credLow = HPDlo(prob)) %>%
#   right_join(d_a, by = c("response"))
  
acor = round(cor(apredictive.pp$MAP, apredictive.pp$empProb), 2)

#pdf(file="../writing/2015/journal-manuscript/figures/AnswererPredictive.pdf",
#         width = 6, height = 3)
answer_plots = (ggplot(apredictive.toplot, aes(x = MAP, y = empProb))
  + theme(text = element_text(size = 20),
          axis.text.x = element_text(angle=90, vjust=1))
  + xlab("Model predicted probability")
  + ylim(0,1)
  + ylab("Empirical Probability")
  + geom_errorbar(aes(ymax = upper_ci, ymin = lower_ci)) 
  + geom_errorbarh(aes(xmax = credHigh, xmin = credLow))
  + geom_point(aes(colour = domain, shape = type))
  + geom_abline(intercept = 0, slope = 1, linetype = "dotted")
  + scale_x_continuous(lim = c(0,1), breaks=c(0,.5,1))
  + ggtitle("Answerer Posterior Predictive")
  + geom_smooth(method = "lm")
  + geom_text(aes(x=.75,y=.25,label=acor))
  + theme_bw())
answer_plots
#dev.off()
```

```{r}
qpredictive<-read.csv("guessingGame/Bayesian/data/BayesianQuestionerAnalysisPredictives_final.csv", sep = ",", row.names = NULL)
qpredictive.samples <- qpredictive[rep(row.names(qpredictive), 
                                       qpredictive$MCMCprob*samples), 1:5] %>%
  mutate(goal = as.character(parameter), 
         question = as.character(value),
         type = as.character(item1),
         domain = as.character(item2)) %>%
  do(mutate(., goal = vectorizedMapGoal(type, goal))) %>%
  do(mutate(., question = vectorizedMapQuestion(type, question))) %>%
  mutate(goal = as.factor(goal), response = as.factor(question)) %>% 
  select(type, domain, goal, response, prob)

qpredictive.pp <- qpredictive.samples %>%
  group_by(type, domain, goal, response) %>%
  summarize(MAP = estimate_mode(prob),
            credHigh = HPDhi(prob),
            credLow = HPDlo(prob)) %>%
  right_join(d_q, by = c("goal","type","domain","response")) 

qcor <- round(cor(qpredictive.pp$MAP, qpredictive.pp$empProb), 2)

pdf(file="../writing/2015/journal-manuscript/figures/QuestionerPredictive.pdf",
        width = 6, height = 3)
question_plots = (ggplot(qpredictive.pp, aes(x = MAP, y = empProb))
  + theme(text = element_text(size = 20),
          axis.text.x = element_text(angle=90, vjust=1))
  + xlab("Model predicted probability")
  + ylim(0,1)
  + ylab("Empirical Probability")
  + geom_errorbar(aes(ymax = upper_ci, ymin = lower_ci)) 
  + geom_errorbarh(aes(xmax = credHigh, xmin = credLow))
  + geom_point(aes(colour = domain, shape = type))
  + geom_abline(intercept = 0, slope = 1, linetype = "dotted")
  + scale_x_continuous(lim = c(0,1), breaks=c(0,.5,1))
  + ggtitle("Questioner Posterior Predictive")
  + geom_smooth(method = "lm")
  + geom_text(aes(x=.75,y=.25,label=paste("r=",qcor)))
  + theme_bw())
question_plots
dev.off()
```