---
title: "exp1_learning"
output: html_document
---

Set wd

```{r}
library(knitr)
opts_knit$set(root.dir = '/Users/rxdh/Box Sync/stanford/research/goodman/q&a/experiment1/')
setwd("/Users/rxdh/Box Sync/stanford/research/goodman/q&a/experiment1/")
library(tidyr)
library(plyr)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(MultinomialCI)
```

Experiment data analysis
--------------------------

Load and clean data. We remove people who self-identify as 'confused' 

```{r}
d1 = read.csv("versions/experiment1/data/q_and_a_nomammal1-trials.tsv",  sep = '\t')
# Remove people who were confused...
ps1 = read.csv("versions/experiment1/data/q_and_a_nomammal1-subject_information.tsv", sep = '\t')
# we only want to exclude people who specifically recorded that they were confused,
# keeping people who just left the response box blank.
nonconfused_ps1 <- (ps1 %>% 
                   mutate(asses2 = ifelse(is.na(asses), "None", asses)) %>% 
                   filter(asses2 != 1))$workerid
d1 = filter(d1, workerid %in% nonconfused_ps1)

d2 = read.csv("versions/experiment1/data/q_and_a_nomammal2-trials.tsv",  sep = '\t')
ps2 = read.csv("versions/experiment1/data/q_and_a_nomammal2-subject_information.tsv", quote = "", sep = '\t')
nonconfused_ps2 <- (ps2 %>% 
                   mutate(asses2 = ifelse(is.na(asses), "None", asses)) %>% 
                   filter(asses2 != 1))$workerid
d2 = filter(d2, workerid %in% nonconfused_ps2)
d = rbind(d1, d2)
cat("there were", 125 - (length(nonconfused_ps1) + length(nonconfused_ps2)), 
    "confused participants")
```


Add order column

```{r}
d$order = rep(c(rep("first",4),rep("second",4)), length(d$workerid)/8)
```

Tidy up questioner data...

```{r}
d_q_first = d %>% 
      filter(trial_type == 'question') %>%
  filter(order == 'first') %>%
      mutate(response = ordered(response, levels = c("dalmatian", "dog", 
                                                     "pet", "animal"))) %>%
      mutate(utterance = ordered(qud, levels = c("dalmatian", "poodle", 
                                                 "siamese cat", "whale"))) %>%
      group_by(qud) %>%
      mutate(group_size = n()) %>%
      group_by(qud, response) %>% # collapse over participants
      summarize(count = n(), emp_prob = n() / mean(group_size))%>%
      select(qud, response, count, emp_prob)

d_q_second = d %>% 
      filter(trial_type == 'question') %>%
  filter(order == 'second') %>%
      mutate(response = ordered(response, levels = c("dalmatian", "dog", 
                                                     "pet", "animal"))) %>%
      mutate(utterance = ordered(qud, levels = c("dalmatian", "poodle", 
                                                 "siamese cat", "whale"))) %>%
      group_by(qud) %>%
      mutate(group_size = n()) %>%
      group_by(qud, response) %>% # collapse over participants
      summarize(count = n(), emp_prob = n() / mean(group_size))%>%
      select(qud, response, count, emp_prob)
d_q_second

# Hadley Wickham hasn't fixed summarize to take drop = F yet, so we have to re-insert rows with p = 0
d_q = d_q %>%
      right_join(expand.grid(response  = levels(d_q$response),
                             qud = levels(d_q$qud))) %>%
      mutate(emp_prob = ifelse(is.na(emp_prob), 0, emp_prob)) 

# get confidence intervals in the stupidest way possible...
qud_levels = unique(d_q$qud)
cis = rbind(multinomialCI(subset(d_q, qud == qud_levels[1])$count, .05),
            multinomialCI(subset(d_q, qud == qud_levels[2])$count, .05),
            multinomialCI(subset(d_q, qud == qud_levels[3])$count, .05),
            multinomialCI(subset(d_q, qud == qud_levels[4])$count, .05))
colnames(cis) <- c("lower_ci", "upper_ci")
d_q = cbind(d_q, cis)
```

Tidy up answerer data...

```{r}
d_a_first = d %>% 
      filter(trial_type == 'ans:') %>%
    filter(order == 'first') %>%
      filter(response != "None", response != "") %>% 
      mutate(response = as.numeric(factor(response))) %>%
      mutate(response = as.character(mapply(function(str, num) strsplit(str,",")[[1]][num], 
                                    as.character(world_state), response))) %>%
      mutate(response = ordered(response,
                                levels=c("dalmatian","poodle","siamese cat","whale"))) %>%
      mutate(utterance = ordered(utterance,
                                 levels = c("dalmatian", "dog", "pet", "animal"))) %>%
      group_by(utterance) %>%
      mutate(group_size = n()) %>%
      group_by(utterance, response) %>% # collapse over participants
      summarize(count = n(), emp_prob = n() / mean(group_size))%>%
      select(utterance, response, emp_prob, count) %>%
  mutate(order = "first")
d_a_first


d_a_second = d %>% 
      filter(trial_type == 'ans:') %>%
    filter(order == 'second') %>%
      filter(response != "None", response != "") %>% 
      mutate(response = as.numeric(factor(response))) %>%
      mutate(response = as.character(mapply(function(str, num) strsplit(str,",")[[1]][num], 
                                    as.character(world_state), response))) %>%
      mutate(response = ordered(response,
                                levels=c("dalmatian","poodle","siamese cat","whale"))) %>%
      mutate(utterance = ordered(utterance,
                                 levels = c("dalmatian", "dog", "pet", "animal"))) %>%
      group_by(utterance) %>%
      mutate(group_size = n()) %>%
      group_by(utterance, response) %>% # collapse over participants
      summarize(count = n(), emp_prob = n() / mean(group_size))%>%
      select(utterance, response, emp_prob, count) %>%
      mutate(order= 'second')
d_a_second 
# Hadley Wickham hasn't fixed summarize to take drop = F yet, so we have to re-insert rows with p = 0
d_a = d_a %>% 
      right_join(expand.grid(response  = levels(d_a$response),
                             utterance = levels(d_a$utterance))) %>%
      mutate(emp_prob = ifelse(is.na(emp_prob), 0, emp_prob)) 
utterance_levels = unique(d_a$utterance)
cis = rbind(multinomialCI(subset(d_a, utterance == utterance_levels[1])$count, .05),
            multinomialCI(subset(d_a, utterance == utterance_levels[2])$count, .05),
            multinomialCI(subset(d_a, utterance == utterance_levels[3])$count, .05),
            multinomialCI(subset(d_a, utterance == utterance_levels[4])$count, .05))
colnames(cis) <- c("lower_ci", "upper_ci")
d_a = cbind(d_a, cis)
```

Some chi-squared tests
----------------------

For each distribution, we run a chi-squared test:

```{r}
overall_distribution = (d %>% filter(trial_type == "question") %>% group_by(response) %>% tally)$n
test_dal_q = chisq.test(subset(d_q, qud == "dalmatian")$count) #p = overall_distribution/sum(overall_distribution))
test_dal_q
test_poodle_q = chisq.test(subset(d_q, qud == "poodle")$count)
test_poodle_q
test_cat_q = chisq.test(subset(d_q, qud == "siamese cat")$count)
test_cat_q
test_fish_q = chisq.test(subset(d_q, qud == "whale")$count)
test_fish_q

test_dal_a = chisq.test(subset(d_a, utterance == "dalmatian")$count) 
test_dal_a
test_dog_a = chisq.test(subset(d_a, utterance == "dog")$count)
test_dog_a
test_mammal_a = chisq.test(subset(d_a, utterance == "pet")$count)
test_mammal_a
test_animal_a = chisq.test(subset(d_a, utterance == "animal")$count)
test_animal_a
```

Model + data bar plots
----------------------

Plot for pragmatic questioner. These bar graphs will help show what our model is getting right and what it's getting wrong.

```{r}
# fitted_data = (prag_quest_fits %>% rename(model_prob =pragmatic_prob))
# plot_title = "Pragmatic_Questioner"
fitted_data = (exp_quest_fits %>% rename(model_prob = explicit_prob)) 
plot_title = "Explicit_Questioner"

new_labels = as.factor(sapply(X = fitted_data$qud, FUN = function(v) {return(paste("qud:", v))}))
fitted_data$facet_label = ordered(new_labels,
                             levels = c("qud: dalmatian", "qud: poodle", 
                                        "qud: siamese cat", "qud: whale"))
q_comparison <- fitted_data %>% 
  select(qud, response, emp_prob, upper_ci, lower_ci, model_prob, facet_label) %>%
  rename(empirical = emp_prob, model = model_prob) %>%
  gather(src, prob, empirical, model) 
print(q_comparison)
# Hack to set confidence intervals to 0 for the model
q_comparison[q_comparison$src == "model",]$upper_ci = q_comparison[q_comparison$src == "model",]$prob
q_comparison[q_comparison$src == "model",]$lower_ci = q_comparison[q_comparison$src == "model",]$prob
name = paste("../writing/2015/cogsci/", plot_title, ".pdf", sep = '')
pdf(name)
dodge <- position_dodge(width=0.9)
g4<-(ggplot(q_comparison, aes(x=response, y=prob, fill=src)) 
    #+ scale_y_continuous(limits = c(0,.3))
    + geom_bar(stat='identity', position=dodge)
    + geom_errorbar(aes(ymax = upper_ci, ymin = lower_ci), 
                    position=dodge, width = .25)
    + ylim(-.1, 1.1)
    + scale_fill_grey()
    + theme_bw(base_size = 20)
    + theme(axis.text.x = element_text(angle=90, vjust=1))
    + ggtitle(plot_title)
    + facet_wrap(~facet_label))
g4
dev.off()
```

Now, plot for answerer model:

```{r}
fitted_data = (prag_ans_fits %>% rename(model_prob = pragmatic_prob)) 
plot_title = "Pragmatic_Answerer"
# fitted_data = (exp_ans_fits %>% rename(model_prob = explicit_prob)) 
# plot_title = "Explicit_Answerer"

new_labels = as.factor(sapply(X = fitted_data$utterance, FUN = function(v) {return(paste("utterance:", v))}))
fitted_data$facet_label = ordered(new_labels, 
                              levels = c("utterance: dalmatian", "utterance: dog", 
                                         "utterance: pet","utterance: animal"))
a_comparison <- fitted_data %>% 
  select(utterance, response, emp_prob, upper_ci, lower_ci, model_prob, facet_label) %>%
  rename(empirical = emp_prob, model = model_prob) %>%
  gather(src, prob, empirical, model) 

a_comparison[a_comparison$src == "model",]$upper_ci = a_comparison[a_comparison$src == "model",]$prob
a_comparison[a_comparison$src == "model",]$lower_ci = a_comparison[a_comparison$src == "model",]$prob
name = paste("../writing/2015/cogsci/", plot_title, ".pdf", sep = '')
pdf(name)
dodge <- position_dodge(width=0.9)
g4<-(ggplot(a_comparison, aes(x=response, y = prob, fill=src)) 
     + geom_bar(stat='identity', position=position_dodge())
     + geom_errorbar(aes(ymax = upper_ci, ymin = lower_ci), 
                    position=dodge, width = .25)
     + scale_fill_grey()
     + theme_bw(base_size = 20)
     + ggtitle(plot_title)
     + theme(axis.text.x = element_text(angle=90, vjust=1))
     + facet_wrap(~facet_label))
g4
dev.off()
```
