---
title: "experiment1_onlyPets"
output: html_document
---

```{r}
library(knitr)
opts_knit$set(root.dir = '/Users/rxdh/Box Sync/stanford/research/goodman/q&a/experiment1/')
setwd("/Users/rxdh/Box Sync/stanford/research/goodman/q&a/experiment1/")
library(tidyr)
library(plyr)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(MultinomialCI)
```

Import data

```{r}
d = read.csv("versions/experiment1_onlyPets_v2/data/q_and_a_onlyPets_v2-trials.tsv",  sep = '\t')
ps = read.csv("versions/experiment1_onlyPets_v2/data/q_and_a_onlyPets_v2-subject_information.tsv", sep = '\t')
nonconfused_ps <- (ps %>% 
                   mutate(asses2 = ifelse(is.na(asses), "None", asses)) %>% 
                  filter(language != "Mandarin") %>%
                    filter(language != "") %>%
                   filter(asses2 != 1))$workerid
cat("We removed", length(ps$workerid) - length(nonconfused_ps), "due to confusion")
d = filter(d, workerid %in% nonconfused_ps1)
d$first = rep(c(0,1), length(d)/2)
```

plot it... 

```{r}
ggplot(d, aes(x = response)) + geom_bar(stat = "bin") + facet_wrap(~ qud)
```

chi-squared: do people really say "cat" more than "dalmatian" for poodle?

```{r}
poodle_counts <- subset(d, qud == "poodle") %>%
  group_by(response) %>%
  tally
chisq.test(poodle_counts$n)
```

Not as strong if we just look at first-timers, though...

```{r}
d_firsts <- subset(d, first == 0)
ggplot(d_firsts, aes(x = response)) + geom_bar(stat = "bin") + facet_wrap(~ qud)
```